---
abstract: unknown
author:
  - unknown
build_requires:
  Data::UUID::MT: 0
  Hash::Merge: 0
  Mojolicious: 2.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex-IO-CMDB
no_index:
  directory:
    - t
    - inc
requires:
  Data::UUID::MT: 0
  Hash::Merge: 0
  Mojolicious: 2.98
resources:
  repository: https://github.com/krimdomu/rex-io-cmdb
version: v0.0.3
